name: smart_elderly_care_mobile
description: 智慧养老平台 Flutter 客户端
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  amap_flutter_base: ^3.0.0
  amap_flutter_location: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
